# Generated by Django 5.2.6 on 2025-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="cloud",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="description",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="precipitation_probability",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="relative_humidity_2m",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="weather_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_speed_10m",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
