# Generated by Django 5.2.6 on 2025-09-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_remove_weatherdata_cloud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=50)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="WeatherDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("weather_code", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherHourly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_2m", models.FloatField()),
                ("relative_humidity_2m", models.IntegerField()),
                ("precipitation_probability", models.IntegerField()),
                ("wind_speed_10m", models.FloatField()),
                ("weather_code", models.IntegerField()),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather.weatherday",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
