# Generated by Django 5.2.6 on 2025-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_city_weatherday_weatherhourly_delete_weatherdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="geometry_id",
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
