# Generated by Django 5.2.6 on 2025-09-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0004_city_geometry_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherday",
            old_name="weather_code",
            new_name="weather_code_day",
        ),
        migrations.AddField(
            model_name="weatherday",
            name="weather_code_evening",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
