# Generated by Django 5.2.6 on 2025-09-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0005_rename_weather_code_weatherday_weather_code_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherhourly",
            name="hour",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
