# Generated by Django 5.2.6 on 2025-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0006_weatherhourly_hour"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_no_sign", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name="City",
            new_name="Location",
        ),
        migrations.RenameField(
            model_name="weatherday",
            old_name="city",
            new_name="location",
        ),
    ]
