# Generated by Django 5.2.6 on 2025-09-10 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0007_locationreference_rename_city_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherday",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_daily",
                to="weather.location",
            ),
        ),
        migrations.AlterField(
            model_name="weatherhourly",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_hourly",
                to="weather.weatherday",
            ),
        ),
    ]
