# Generated by Django 5.2.6 on 2025-09-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0008_alter_weatherday_location_alter_weatherhourly_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherDescription",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="weatherday",
            name="location",
        ),
        migrations.CreateModel(
            name="WeatherDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_daily",
                        to="weather.locationreference",
                    ),
                ),
                (
                    "weather_code_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="day_description",
                        to="weather.weatherdescription",
                    ),
                ),
                (
                    "weather_code_evening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="night_description",
                        to="weather.weatherdescription",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="weatherhourly",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_hourly",
                to="weather.weatherdaily",
            ),
        ),
        migrations.AlterField(
            model_name="weatherhourly",
            name="weather_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hour_description",
                to="weather.weatherdescription",
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="WeatherDay",
        ),
    ]
