# Generated by Django 5.2.6 on 2025-09-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0009_weatherdescription_remove_weatherday_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherdaily",
            name="weather_code_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weather_in_day",
                to="weather.weatherdescription",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdaily",
            name="weather_code_evening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weather_in_night",
                to="weather.weatherdescription",
            ),
        ),
        migrations.AlterField(
            model_name="weatherhourly",
            name="weather_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weather_in_hour",
                to="weather.weatherdescription",
            ),
        ),
    ]
